### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by arturious** [sigex-kz/ncalayer-js-client#10]
подскажите пожалуйста где ошибка
```javascript
import type { LoaderFunction, ErrorBoundaryComponent } from "@remix-run/node";
import { json } from "@remix-run/node";
import {
	useLoaderData,
	useCatch,
	Outlet,
	Link,
	useNavigate,
	useActionData,
} from "@remix-run/react";
import { useTranslation } from "react-i18next";
import { useUser } from "~/utils/user-context";
import React, { useState, useEffect } from "react";
import { t } from "i18next";
import { NcaLayer, NcaLayerClient } from "ncalayer-js-client";

import {
	ChevronLeftIcon,
	PaperClipIcon,
	PencilIcon,
} from "@heroicons/react/20/solid";
import { StarIcon } from "@heroicons/react/20/solid";

import { authenticator } from "~/services/auth.server";
import { authToken } from "~/services/session.server";
import { getTrade } from "~/services/trade.server";
import { Trade } from "~/services/types";
import { LotDetail, getLot } from "~/services/lot.server";
import { Lot } from "~/services/types";
import Header2 from "~/components/layout/Header2";

// Определите NcaLayer за пределами компонента
const ncaLayer = new NcaLayer({
	host: "localhost",
	port: 13579,
});

export let loader: LoaderFunction = async ({ params, request }) => {
	const token: typeof authToken = await authenticator.isAuthenticated(request, {
		failureRedirect: "/login",
	});
	const number = params.number ? params.number : null;
	if (!number) throw new Response("Not Found", { status: 404 });
	const trade: Trade | null = token ? await getTrade(token, number) : null;

	const lotDetail: LotDetail | null =
		token && trade ? await getLot(token, trade.symbol) : null;
	if (!lotDetail) throw new Response("Not Found", { status: 404 });

	return json({ trade, lotDetail });
};

export default function Route() {
	const { trade, lotDetail } = useLoaderData();
	const [xmlData, setXmlData] = useState("");
	const [signedXml, setSignedXml] = useState("");

	useEffect(() => {
		const generatedXML = `<Name>${lotDetail.lot.name}</Name>`;
		setXmlData(generatedXML);
	}, [lotDetail]);

	const handleSignXml = async () => {
		try {
			const base64EncodedData = btoa(xmlData); // Преобразуйте xmlData в base64EncodedData
			const base64EncodedSignature = await connectAndSign(base64EncodedData);

			if (base64EncodedSignature) {
				setSignedXml(atob(base64EncodedSignature)); // Декодируйте подписанные данные из base64
			} else {
				console.error("Error signing XML");
			}
		} catch (error) {
			console.error("Error signing XML:", error);
		}
	};

	return (
		<>
			<Header2 title={`Подписать ${trade.number}`}>
				<Link
					to={`/trades/${trade.number}`}
					className="inline-flex items-center justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-100">
					<ChevronLeftIcon className="-ml-1 mr-2 h-5 w-5" aria-hidden="true" />
					<span className="whitespace-nowrap">
						{t("markets.button.goback")}
					</span>
				</Link>
			</Header2>

			<div>
				<textarea name="xmlData" rows={4} cols={50} value={xmlData} readOnly />
				<button onClick={handleSignXml}>Подписать XML</button>
				<textarea
					name="signedXml"
					rows={4}
					cols={50}
					value={signedXml}
					readOnly
				/>
			</div>
		</>
	);
}

async function connectAndSign(base64EncodedData: string) {
	const ncalayerClient = new NcaLayerClient();

	try {
		await ncalayerClient.connect();
	} catch (error) {
		console.error("Error connecting to NCALayer:", error);
		return null;
	}

	let activeTokens;
	try {
		activeTokens = await ncalayerClient.getActiveTokens();
	} catch (error) {
		console.error("Error getting active tokens:", error);
		return null;
	}

	const storageType = activeTokens[0] || NcaLayerClient.fileStorageType;

	let base64EncodedSignature;
	try {
		base64EncodedSignature = await ncalayerClient.createCAdESFromBase64(
			storageType,
			base64EncodedData
		);
	} catch (error) {
		console.error("Error creating CAdES signature:", error);
	}

	return base64EncodedSignature;
}

``` 
ошибка:
TypeError: import_ncalayer_js_client.NcaLayer is not a constructor
    at Object.<anonymous> (C:\projects\dva\dva-full\frontend\app\routes\trades\$number\sign.tsx:33:18)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at C:\projects\dva\dva-full\frontend\server.js:38:13
    at Layer.handle [as handle_request] (C:\projects\dva\dva-full\frontend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\projects\dva\dva-full\frontend\node_modules\express\lib\router\route.js:144:13)

**Comment by vsenko** [comment]
Скорее всего в том, что в бибилотеке класс определен как `NCALayerClient`, а в примере он используется как `NcaLayerClient`.

**Comment by arturious** [comment]
а как реализовать так чтоб xml при нажатии на кнопку подписать выходило окно выбора файла эцп и полсе выбора в новую форму добавлялись xml и подпись

**Comment by vsenko** [comment]
Вообще тут не лучшее место для обсуждения вопросов напрямую не связанных с этой библиотекой.

Вот пример в котором реализовано подобное: https://github.com/sigex-kz/sigex-qr-signing-client/tree/main/docs Там правда используется подписание через QR, но разница не большая, можно его легко переделать и для NCALayer.
